name: Build Firefox Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version:   14
        cache: 'npm'
    
    - name: Downgrade npm
      run: npm install -g npm@5.2.0
    
    - name: Install dependencies
      run: npm ci


    - name: Install dependencies
      run: npm ci

    - name: Build React App
      run: npm run build

    - name: Install web-ext
      run: npm install --global web-ext

    - name: Build Firefox Extension
      run: web-ext build --source-dir build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: firefox-extension
        path: web-ext-artifacts/
